export const appStrings = {
    appTitle: 'HealthCare',
    appLogoText: 'T',

    rootLink: 'Home',
    doctorLink: 'Find a doctor',
    appsLink: 'Apps',
    testimonialsLink: 'Testimonials',
    aboutLink: 'About us',
    
    bannerTitle1: "Virtual healthcare for you",
    bannerTitle2: "Leading healthcare providers",
    bannerTitle3: "Download our mobile apps",
    bannerText1: "Our service provides progressive, and affordable healthcare, accessible on mobile and online for everyone",
    bannerText2: "We provides progressive, and affordable healthcare, accessible on mobile and online for everyone. To us, it’s not just work. We take pride in the solutions we deliver",
    bannerText3: "Our dedicated patient engagement app and web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely",
    bannerButton1: "Consult today",
    bannerButton2: "Learn more",
    bannerButton3: "Download",

    servicesTitle: "Our services",
    servicesButton: "Learn more",
    servicesDescription: "We provide to you the best choiches for you. Adjust it to your health needs and make sure your undergo treatment with our highly qualified doctors you can consult with us which type of service is suitable for your health",
    serviceTitle1: "Search doctor",
    serviceTitle2: "Online pharmacy",
    serviceTitle3: "Consultatuion",
    serviceTitle4: "Details info",
    serviceTitle5: "Emergency care",
    serviceTitle6: "Tracking",
    serviceDescription1: "Choose your doctor from thousands of specialist, general, and trusted hospitals",
    serviceDescription2: "Buy  your medicines with our mobile application with a simple delivery system",
    serviceDescription3: "Free consultation with our trusted doctors and get the best recomendations",
    serviceDescription4: "Free consultation with our trusted doctors and get the best recomendations",
    serviceDescription5: "You can get 24/7 urgent care for yourself or your children and your lovely family",
    serviceDescription6: "Track and save your medical history and health data ",

    sliderTitle: "What our customer are saying",
    sliderAvatarTitle1: "Edward Newgate",
    sliderAvatarTitle2: "Hyppocrate",
    sliderAvatarTitle3: "Samuel Reinberg",
    sliderAvatarTitle4: "Ivan Pavlov",
    sliderAvatarDescription1: "Founder Circle",
    sliderAvatarDescription2: "Father of Medicine",
    sliderAvatarDescription3: "Doctor of Medical Sciences",
    sliderAvatarDescription4: "Soviet scientist",
    sliderText1: "“Our dedicated patient engagement app and web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely”",
    sliderText2: "“Your food should be medicine, and your medicine should be food”",
    sliderText3: "“The diagnosis can be economical: only the diagnosis that gets the most information with a minimum of research is good”",
    sliderText4: "“Man is the most complex and subtle system. But in order to enjoy the treasures of nature, a person must be healthy, strong and smart”",

    articlesTitle: "Check out our latest article",
    activeArticlesButton: "View all",
    hideArticlesButton: "Hide",
    articleButton: "Read more",
    articleTitle1: "Disease detection, check up in the laboratory",
    articleTitle2: "Herbal medicines that are safe for consumption",
    articleTitle3: "Natural care for healthy facial skin",
    articleText1: "In this case, the role of the health laboratory is very important to do a disease detection...",
    articleText2: "Herbal medicine is very widely used at this time because of its very good for your health...",
    articleText3: "A healthy lifestyle should start from now and also for your skin health. There are some...",

    footerText: "HealthCare provides progressive, and affordable healthcare, accessible on mobile and online for everyone",
    footerBrand: "©HealthCare PTY LTD 2023. All rights reserved",
}




